### ISSUE TITLE
WebChat integration is failing

### ISSUE THREAD

**Issue by jdmevo123** [michalmar/openai-demos-bot-webapp#7]
I have the DIRECT_LINE_TOKEN stored in the env and can see it in the requests. However when i try and load the page i get the following error:

https://directline.botframework.com/v3/directline/conversations fails 
(failed)net::ERR_CONNECTION_REFUSED

Do i need to set anything else besides the DIRECT_LINE_TOKEN?

**Comment by michalmar** [comment]
Hi, there should be also set this variable in the web app you are trying to
deploy (in configuration).

But this repo is no longer being maintained since there has been some
changes in the APIs and more sophisticated interfaces have been developed-
I highly recommend to chase I out this official repo:
https://github.com/microsoft/azurechat
